### PR TITLE
Tweak style of horizontal scroll bars

### PR DESCRIPTION
**Pull request by luzpaz**
Follow-up to 8a69f62214

### CODE REVIEW

**Comment by luzpaz** [comment]
Screenshot of proposed change: image

**Comment by francescmm** [comment]
Hi @luzpaz this only reduces the styles of the horizontal bar whereas the vertical remains the same size. I understand that the height of the screen is an issue, but this size makes it a bit difficult to handle in depending what screen sizes (like high DPI).

**Comment by luzpaz** [comment]
Yea, I didn't figure out how to just isolate the tree vertical dragbar. But IMHO, I think it also looks more sleek being thinner. It's your call though, feel free to close this if you deem it

**Comment by luzpaz** [comment]
Would you be OK if I shrink the size of the vertical bar as well ? Or should I close this PR?

**Comment by francescmm** [comment]
Sure! Let's give it a try! :D

**Comment by luzpaz** [comment]
Sorry, have no time to work on this ATM. I'll close this PR.

**Pull request closed without merging**
